---
abstract: 'Create a simple .sql file for SQLite'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MySQL-Workbench-SQLiteSimple
requires:
  Carp: '0'
  File::Basename: '0'
  File::Spec: '3.40'
  Moo: '1.003001'
  MySQL::Workbench::Parser: '0.03'
  Test::LongString: '0.16'
  perl: '5.010001'
resources:
  bugtracker: http://github.com/reneeb/MySQL-Workbench-SQLiteSimple/issues
  homepage: http://github.com/reneeb/MySQL-Workbench-SQLiteSimple
  repository: git://github.com/reneeb/MySQL-Workbench-SQLiteSimple.git
version: '0.02'
